### ISSUE TITLE
6101 updates for Sem 2020.

### ISSUE THREAD

**Issue by knmnyn** [WING-NUS/cs6101#21]
Great work so far!  Thank you :pray: A few things more to edit.
In the home page:
Change the header from "Biweekly Fri 13:00-15:00 @ Zoom" to "Web, IR and NLP Public Reading Group"
Please add a sentence to disclose the topics of recommendation and conversational systems and their intersection.  Please bold the topics.
In the past semesters page:
Please fix the typo in the AY 2020/20201 line at the top
Add a table of contents at the top of this page that has local anchors to the separate semesters and title them with their content. e.g.,
AY 2020/2021 Semester 1 (2010): Advanced General NLP Topics II
AY 2020/2021 Semester 1 (2010): Advanced General NLP Topics I
For the People page:
For any graduate WING member, hyperlink their name to their current home page.

**Comment by YisongMiao** [comment]
Done :D

**Comment by YisongMiao** [comment]
https://github.com/WING-NUS/cs6101/commit/60b10ed4cb89b09b7f210db41e2c1778e17800d8
